#### SETUP ####

setwd("~/Downloads/Data Dissertation")

library(rgdal)
library(rgeos)
library(maptools)
library(sf)
library(raster)
library(eyelinker)
library(httr)
library(jsonlite)
library(rjson)
library(tidyr)
library(countrycode)
library(dplyr)
library(igraph)
library(Rmpfr)
library(netUtils)
library(bipartite)
library(tnet)
library(readr)
library(haven)
library(survival)
library(stringr)
library(data.table)
library(eha)
library(sandwich)
library(lmtest)
library(Hmisc)
library(survminer)
library(foreign)
library(car)
library(tidyverse)
library(broom)
library(GGally)
library(jtools)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
